# Generated by Django 4.2.11 on 2024-04-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_newuser_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUserType',
            new_name='Type',
        ),
    ]
